import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={"bg-gray-100 w-screen h-screen"}>
          <div className={"w-1/2 mx-auto"}>{children}</div>
        </div>
      </body>
    </html>
  );
}
